# Generated by Django 6.0.6 on 2026-07-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0008_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(choices=[('Kochi', 'Kochi'), ('Thrissur', 'Thrissur'), ('Kozhikode', 'Kozhikode'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=100),
        ),
    ]
